// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HomeController from "./home_controller"
application.register("home", HomeController)

import LikesController from "./likes_controller"
application.register("likes", LikesController)

// import LikesServicesController from "./likes_services_controller"
// application.register("likes-services", LikesServicesController)

//import MapController from "./map_controller"
// application.register("map", MapController)
